<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            'Agarpara',
            'AHRITALA',
            'Airport Gate No 1',
            'Airport Gate No 3',
            'Ajaynagar',
            'Alambazar',
            'Alipore',
            'Ariadaha',
            'Avisikta',
            'Baghajatin',
            'Baghbazar',
            'Bagmari',
            'Baguiati Haldiram',
            'Baguiati Jessore Road',
            'Ballugunj station',
            'Bally Ghat Station',
            'Bally Halt Station',
            'BallyStation',
            'Bangur Avenue',
            'Bankra',
            'Bansdroni',
            'Baranagar',
            'Bediapara',
            'Behala Chowrasta',
            'Behala Police Station',
            'Belgachia Metro Station',
            'Belgharia',
            'Beliaghata Main Road',
            'Bengal Chemical',
            'Bhavwanipore',
            'Bijoygarh',
            'BIKRAMGARH',
            'Birati',
            'Bonohoogly',
            'Bowbazar',
            'Burrabazar',
            'Canal Road',
            'Central',
            'Chandi Chowk Metro Station',
            'Chetla',
            'Chinar Park',
            'Chingrighata',
            'Chiria More',
            'City Center 2',
            'CMRI Hospital Ekbalpore',
            'College Street',
            'Dakhineswar Adyapeath',
            'Dakhineswar Metro Station',
            'Desopriyo Park',
            'Dhakuria',
            'Dharmatala',
            'Dumdum Cantonment  Subhas Nagar',
            'Dumdum Cantonment Rajbari',
            'Dumdum Cantonment Station',
            'Dumdum Central Jail',
            'Dumdum Nagerbazar',
            'Dumdum Nortnern Avenue',
            'Dumdum Park Jessore Road',
            'Dumdum Park VIP Road',
            'Dumdum Station',
            'DUMDUMMALROAD',
            'Dunlop Metro Station',
            'Durganagar',
            'Entally',
            'Entally Paddapukur',
            'Esplanade Metro Station',
            'GANGULY BAGAN',
            'Garfa',
            'Garia More',
            'Garia Station',
            'Gariahat More',
            'Girish Park Metro Station',
            'Golf Green',
            'Golpark',
            'Gorabazar',
            'GOURANGANAGAR',
            'Haltu',
            'Haridevpur',
            'HATIARA',
            'HATIBAGAN',
            'HAZRA',
            'Hedua',
            'Howrah Maidan',
            'Howrah Mandirtala',
            'Howrah Station',
            'HYLAND PARK',
            'Jadavpur 8B Stand',
            'Jadavpur Police Station',
            'Jadavpur Santoshpur',
            'Jagatpur',
            'James long Sarani',
            'Jatin Das Park Metro',
            'Jodhpur Park',
            'Jorasanko',
            'Kabardanga',
            'Kaikhali',
            'Kakurgachi',
            'Kalighat Metro',
            'Kalighat Temple',
            'Kalikapur',
            'Kalindi',
            'KALIPARK',
            'KAMARHATI',
            'Kasba',
            'Kashipore',
            'Kestopur',
            'Kestopur Krishnapur',
            'Kestopur Rabindrpally',
            'Khanna',
            'Khidderpore',
            'KUDGHAT',
            'Lake Gardens',
            'Lake Town Jessore Road',
            'Lake Town VIP Road',
            'Lansdowne',
            'Lenin Sarani',
            'Madhyamgram Chowmatha',
            'Madhyamgram Station',
            'MAHISHBATHAN',
            'Majerhat Station',
            'Manicktala',
            'Mathkol',
            'METROPOLITAN',
            'MG Road Metro Station',
            'Michaelnagar',
            'MINTOPARK',
            'Mominpore',
            'MOULALI',
            'MUCHIBAZAR',
            'Mukundapur',
            'NABANNA',
            'Naktala',
            'Narkeldanga',
            'NAYABAD',
            'Netaji Bhavan Metro',
            'NETAJINAGAR',
            'New Alipore',
            'New Barrackpore',
            'NEW GARIA',
            'New Town Axis Mall',
            'New Town Balaka',
            'New Town Bus stand',
            'New Town DLF 1',
            'New Town DLF 2',
            'New Town Ecospace',
            'New Town Shapoorjee',
            'New Town Uniworld',
            'NIMTA',
            'Nimta Police Station',
            'Noapara Metro Station',
            'PaikPara',
            'Panchanna Gram',
            'Park Circus 7 Point Crossing',
            'PARKCIRCUS',
            'PARKSTREET',
            'Parnashree',
            'Patipukur',
            'Patuli',
            'Pearless Hospital',
            'Phoolbagan',
            'Picnic Garden',
            'Prince Anwar Shah Road',
            'Purbanchal',
            'Rabindra Bharthi University',
            'Rabindra Sarovar Metro',
            'RAJABAZAR',
            'Rajarhat Akankha',
            'Rajarhat Chowmatha',
            'Rajarhat narayanpur',
            'Ranikuthi',
            'Rasbehari',
            'Rathtala',
            'Ripon Street',
            'Ruby',
            'Salt Lake City Center',
            'Salt Lake Karunamoyee Bustand',
            'Salt Lake Stadium',
            'SALTLAKE206',
            'Sarat Bose Road',
            'Science City',
            'Sealdah',
            'Sector V Mahisbathan',
            'Selimpur',
            'Shakespeare Sarani',
            'Shyambazar Metro',
            'Sinthir More',
            'Sodepur',
            'South City Mall',
            'Sovabazar Metro',
            'Sukanta Nagar',
            'Sulekha',
            'Tala Park',
            'TALTALA',
            'Tangra',
            'Taratala Bridge',
            'Teghoria',
            'Tobin Road',
            'Tollugunj Muchipara',
            'Tollygunj Metro Station',
            'Topsia',
            'Ultadanga'
        ];

        $data = [];
        foreach ($locations as $location) {
            $data[] = [
                'name' => $location,
                'slug' => \Str::slug($location), // Generate slug from name
            ];
        }

        DB::table('loaction')->insert($data);
    }
}
